language: python
python:
 - "2.6"
 - "2.7"
install:
 - pip install . --use-mirrors
 - pip install coverage
script: nosetests --with-coverage --cover-package=flask_cache
services:
 - memcached
 - redis-server
